### ISSUE TITLE
Didn't work on my laptop.

### ISSUE THREAD

**Issue by utibenkei** [keijiro/BlazeFaceBarracuda#1]
Hi, thank you for publishing the repository of the wonderful Barracuda project.

I tried BlazeFaceBarracuda on my laptop (Surface-pro / GPU: Intel HD Graphics 620) and it doesn't seem to give me the right results.  No face detection results are displayed at all.
I tested other Barracuda examples and it seems that the BlazePalmBarracuda has the same problem, but the other UltraFaceBarracuda, BodyPixBarracuda, YoloV4TinyBarracuda, FaceLandmarkBarracuda, etc. are fine.
But strangely enough, another desktop PC (GPU: NVIDIA GeForce GTX 1050) had no problem in all cases.

When I compared the post-processed output from both environments, there was a difference, so it seems there is a problem at the post-processing stage. Is there a solution to this?

**Comment by keijiro** [comment]
I wonder if the old implementation works on it, like this version:
https://github.com/keijiro/BlazeFaceBarracuda/tree/872786b14c65ab95c215bff14e8fb2b264bdd029

**Comment by utibenkei** [comment]
After further investigation, I found that the same problem occurs in "TinyYOLOv2Barracuda", but I could not identify the cause.
Later, I changed the Graphics API used in the project from the default "Direct3D11" to "Vulkan", and the problem disappeared.
Now that I have found a solution, I will close this issue.
Thank you very much for your help.
