### ISSUE TITLE
GPU to CPU readback slow with a heavy scene

### ISSUE THREAD

**Issue by YelovSK** [keijiro/BlazeFaceBarracuda#2]
I'm sorry if this is an issue with Unity itself and not the implementation.
What I noticed is that the UpdatePost2ReadCache() function in [FaceDetector.cs](https://github.com/keijiro/BlazeFaceBarracuda/blob/main/Packages/jp.keijiro.mediapipe.blazeface/Script/FaceDetector.cs) is quite slow with a complex scene (object with 1 million vertices).

- Face detection + getting output takes around 5ms.
- Render of the scene without face detection takes around 8ms.
- Face detection + render of the scene takes around 90ms. The inference is the same at 4ms, but GPU to CPU readback goes from 2ms to 30ms.

5ms + 8ms should be 13ms, not 90ms. Is there any way to speed up the output? Thanks.

**Comment by keijiro** [comment]
That's why you should avoid GPU to  CPU readback in general. Please understand that this sample project is just for testing the model. You may have to construct a GPU-side only implementation like I did in the FaceMeshBarracuda pipeline.

https://github.com/keijiro/FaceMeshBarracuda
