### ISSUE TITLE
Unity Klak dependency missing

### ISSUE THREAD

**Issue by jull360** [keijiro/BlazeFaceBarracuda#4]
Hi,

When I try to download [jp.keijiro.mediapipe.blazeface (https://github.com/keijiro/BlazeFaceBarracuda/tree/main/Packages/jp.keijiro.mediapipe.blazeface) package and put it into Packages.
I get the following Error : jp.keijiro.klak.nnutils (dependency): Package [jp.keijiro.klak.nnutils@1.1.0] cannot be found

thank you

**Comment by keijiro** [comment]
You should use PackageManager to solve the dependencies correctly.

I haven't written detailed instructions in this repository (sorry, that's my laziness), but you can follow the same steps in other my repositories, [like this](https://github.com/keijiro/KlakNDI/blob/main/README.md) (please check the "How To Install" section).

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it if it still reproduces.

**Comment by jull360** [comment]
thank you it almost solved everything !
I still have that one issue
: Assets\Scripts\FaceTracking\Marker\KeyPointsUpdater.cs(9,36): error
CS0426: The type name 'Detection' does not exist in the type 'FaceDetector'

**Comment by Cheren15** [comment]
Same issue as up, old version works fine.
